# Generated by Django 5.1.6 on 2025-03-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='extra_field',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='total_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total_hours',
            field=models.IntegerField(default=0),
        ),
    ]
