# Generated by Django 5.1.6 on 2025-03-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare_app', '0002_booking_booking_id_booking_extra_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(editable=False, max_length=10, null=True, unique=True),
        ),
    ]
